language: csharp
solution: RSOI.sln
dotnet:
  - 2.1.300 # Latest 2.1 Runtime
  
stages:
  - name: test


jobs:
  include:
    - stage: test
      install: 
      script:
        - cd ./Rsoi.Test
        - dotnet test